language: php

php:
  - 7.3

install:
  # Install PHPCS
  - composer global require "squizlabs/php_codesniffer"

  
before_script:
  - phpcs --version
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpcs --standard=PSR2 --extensions=php app
  - vendor/bin/phpunit