language: php

php:
  - 7.3

install:
  # Install PHPCS

  
before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - php artisan key:generate

script:
  - phpcs --standard=PSR2 --extensions=php app
  - vendor/bin/phpunit